spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${DBID}
    password: ${DBPW}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${FILE_PATH}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        format_sql: true
    show-sql: true
  profiles:
    active: dev, db-maria