spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 12
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\\Temp\\spring_uploaded_file
  jpa:
    database: H2
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    s3:
      bucket: bestofthebest11
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAZF3SFNWZUJW3WIM2
      secretKey: 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