spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/filelist
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\\Temp\\spring_uploaded_file
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        format_sql: true
    show-sql: true
  profiles:
    active: dev, db-maria


#cloud:
#  aws:
#    s3:
#      bucket: bestofthebest11
#    stack.auto: false
#    region.static: ap-northeast-2
#    credentials:
#      accessKey: AKIAZF3SFNWZUJW3WIM2
#      secretKey: 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