spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  datasource:
    driver-class-name: ${DB_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${SPRING_DATASOURCE_URL}
    username: ${ROCKET_DB_ID}
    password: ${ROCKET_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

  redis:
    host: ${REDIS_DATASOURCE_URL:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:dev}

  data:
    web:
      pageable:
        default-page-size: 10

springdoc:
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  packages-to-exclude:
  paths-to-exclude:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
