spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${MARIA_DB_ID}
    password: ${MARIA_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none

  data:
    web:
      pageable:
        default-page-size: 10

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
