FROM python:3.10-alpine

WORKDIR /app/

RUN apk add --no-cache --virtual .pynacl_deps build-base python3-dev libffi-dev
RUN pip3 install --upgrade pip && pip3 install --upgrade setuptools && pip3 install checkov==2.3.306

COPY script/scanner_entrypoint.sh /app/scanner_entrypoint.sh

ENTRYPOINT ["checkov","-o","json","-d", "./"]
