server:
  port: 8082

spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:password}

redis:
  mode: single
  nodes:
    - ${REDIS_HOST:redis://127.0.0.1:6379}
  queue:
    max: 7

docker:
  host:
    ssl:
    unix: "unix:///var/run/docker.sock"
  volume:
    host: ${HOST_VOLUME_PATH:./nas/uploads}
    container: ${CONTAINER_VOLUME_PATH:/app/uploads}
