spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: ${DB_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${SPRING_DATASOURCE_URL}
    username: ${ROCKET_DB_ID}
    password: ${ROCKET_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

  redis:
    host: ${REDIS_DATASOURCE_URL:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:password}

docker:
  host:
    ssl:
    unix: "unix:///var/run/docker.sock"
  volume:
    host:
    container: "/app"
