name: Main Build CI

# 추후, input 을 통해서 여러 모듈을 일괄 관리할 예정

on:
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - '!.github/**'
      - '!**.md'
      - '!**gradle**'
      - '!config/**'
      - '!answers/**'
      - '!.yamllint'
      - 'scanhistory/**'
    types: [ opened, closed ]
env:
  SERVICE_NAME: scanhistory

permissions:
  id-token: write
  contents: read  # This is required for actions/checkout

jobs:
  git-leaks:
    uses:
      money-driven-development/rocket23/.github/workflows/template-git-leaks.yaml@dev
    secrets:
      TOKEN_FOR_CICD: ${{ secrets.TOKEN_FOR_CICD }}

  gradle-build:
    uses:
      money-driven-development/rocket23/.github/workflows/template-gradle-build.yaml@dev
    needs: [ git-leaks ]
    secrets:
      DOCKER_REPO: ${{secrets.DOCKER_REPO}}
      DOCKER_REGISTRY: ${{secrets.DOCKER_REGISTRY}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
      SERVICE_NAME: scanhistory
