name: Docker Build CI

# 추후, input 을 통해서 여러 모듈을 일괄 관리할 예정

on:
  pull_request:
    branches: ["main", "dev"]
    paths:
      - '!.github/**'
      - '!**.md'
      - '!**gradle**'
      - '!config/**'
      - '!answers/**'
      - '!.yamllint'
      - 'docker/**'
    types: [opened, closed]

permissions:
  id-token: write
  contents: read  # This is required for actions/checkout

jobs:
  git-leaks:
    uses: money-driven-development/rocket23/.github/workflows/template-git-leaks.yml@dev
    secrets:
      TOKEN_FOR_CICD: ${{ secrets.TOKEN_FOR_CICD }}

  gradle-build:
    uses: money-driven-development/rocket23/.github/workflows/template-gradle-build.yml@main
    needs: [app-scan, git-leaks]
    secrets:
      SERVICE-NAME: file